### ISSUE TITLE
Document keybase steps

### ISSUE THREAD

**Issue by adwhit** [nsriram/lambda-the-terraform-way#4]
Hi, thanks for the great tutorial.

I got a bit stuck  on the initial setup, having never heard of keybase before (and still not really understanding what it is). I eventually got it working through the following steps:

* Install keybase (duh)
* Create an account
* Open up the People tab, go to Edit Profile
* Click "Add pgp key"
* Input fake email
* Generate the key
* Close keybase (but DO NOT log out)

Now when running `terraform apply`, the `keybase_id` to give is your keybase username. As I understand it, terraform will query your local keybase install and get a pgp key from it.

It might be useful to add these steps to the tutorial - either way, hopefully this issue will help others.

**Comment by nsriram** [comment]
@adwhit The link for keybase setup is available in the document. Closing the issue.
